### PR TITLE
Metamask download location

### LINKED ISSUE #41: Error: ENOENT: no such file or directory, mkdir '/var/task/bot/node_modules/@chainsafe/dappeteer/metamask/download
Hi, 
Is it possible to somehow change the extraction directory where the download is done?

`ERRROR	Unhandled Promise Rejection 	{"errorType":"Runtime.UnhandledPromiseRejection","errorMessage":"Error: ENOENT: no such file or directory, mkdir '/var/task/bot/node_modules/@chainsafe/dappeteer/metamask/download'","reason":{"errorType":"Error","errorMessage":"ENOENT: no such file or directory, mkdir '/var/task/bot/node_modules/@chainsafe/dappeteer/metamask/download'","code":"ENOENT","errno":-2,"`

The fs we have is RO, where the node_modules are placed as it is already a bundled application 
So, I think the file doesn't exist, because the download failed (and..there is no error saying about it)

Thanks

### PR DESCRIPTION
**Pull request by BeroBurny**
### PR Checklist

- [x] I have run linter locally
- [x] I have run unit and integration tests locally
- [x] Rebased to master branch / merged master

### Changes
- implement custom download path param for metamask
- update docs

### Issues

Closes #41

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -47,10 +48,10 @@ export type TransactionOptions = {
  * */
 export async function launch(
   puppeteerLib: typeof puppeteer,
-  { args, ...rest }: LaunchOptions = {},
+  { args, metamaskLocation, ...rest }: LaunchOptions = {},
```
Comment (mpetrunic) [inline src/index.ts:51]: allow env to override metamaskLocation this for CI purposes
also rename ti to downloadLocation or metamaskDownloadLocation

Comment (BeroBurny) [reply src/index.ts:51]: > allow env to override metamaskLocation this for CI purposes

Somewhere in `js` developer need to use `launch` and there he can set env variables and they wish.

> also rename ti to downloadLocation or metamaskDownloadLocation

if a user manually download metamask he can set a path to that location, its is not exclusive for download
