### PR TITLE
fix: update ganache, fix test depending on goerli

### LINKED ISSUE #141: Do not run test against Goerli
https://github.com/ChainSafe/dappeteer/blob/master/test/test.spec.ts#L172

Setup localnode and test against local network

### PR DESCRIPTION
**Pull request by mpetrunic**
**Short description of work done**

### PR Checklist

- [ ] I have run linter locally
- [ ] I have run unit and integration tests locally
  - [ ] Update configuration the newest version (readme and const)
- [ ] Rebased to master branch / merged master

### Changes

- _EXAMPLE - Removed basic auth from the controller_

### Issues

Closes #141

### CODE REVIEW

**Comment by mpetrunic** [comment]
Will cherry pick this fix from unstable to master after merged^^

File: src/metamask/confirmTransaction.ts [hunk 1]
```diff
@@ -5,6 +5,8 @@ import { clickOnButton, typeOnInputField } from '../helpers';
 
 import { GetSingedIn } from './index';
 
+const MIN_GAS = 21000;
```
Comment (BeroBurny) [inline src/metamask/confirmTransaction.ts:8]: why is minimal gas hardcoded to fixed value?

File: src/helpers/actions.ts [hunk 2]
```diff
@@ -39,18 +39,36 @@ export const clickOnLogo = async (page: Page): Promise<void> => {
...
 
+/**
+ *
+ * @param page
+ * @param label
+ * @param text
+ * @param clear
+ * @param excludeSpan
+ * @param optional
+ * @returns true if found and updated, false otherwise
```
Comment (BeroBurny) [inline src/helpers/actions.ts:50]: can you point usage of return value?

**Review by BeroBurny — COMMENTED** [review]
LGTM but I have some questions to understand the reasoning for it.

File: src/metamask/confirmTransaction.ts (hunk 1 above)
Comment (mpetrunic) [reply src/metamask/confirmTransaction.ts:8]: That is the value enforced by metamask (and ethereum ), lower than that Metamask validation will disable the Save button and it also makes sense because tx cannot execute.
image

File: src/helpers/actions.ts (hunk 2 above)
Comment (mpetrunic) [reply src/helpers/actions.ts:50]: When filling gas details pre-eip1559, the user might submit priority which would try to write a non-existing field.

File: src/metamask/confirmTransaction.ts (hunk 1 above)
Comment (BeroBurny) [reply src/metamask/confirmTransaction.ts:8]: then we should do additional research on what is a case of other `EVM` chains

Comment (mpetrunic) [reply src/metamask/confirmTransaction.ts:8]: It doesn't really matter as metamask won't allow lower value anyways haha
